SIPUS/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SIPUS.Models;

namespace SIPUS.Controllers
{
    public class BooksController : Controller
    {
        //BaseContext db = new BaseContext();

        private readonly BaseContext _context;

        public BooksController(BaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetDataBooks()
        {
            var book = _context.Books.Where(x=>x.isActive == true).ToList();
            

            return Json(new { data = book });
        }

        [HttpPost]
        public IActionResult Create([FromBody]Books books)
        {
            var message = "";
            try
            {
                books.CreateDate = DateTime.UtcNow;
                books.isActive = true;
                _context.Books.Add(books);
                _context.SaveChanges();
                message = "Sukses";

                return Json(message);
            }
            catch (Exception ex)
            {
                message = "Error";
                return Json(message);
            }
        }

        public IActionResult GetById(int Id)
        {
            return Json(new { data = _context.Books.Find(Id) });
        }

        public IActionResult Update([FromBody]Books books)
        {
            var message = "";
            try
            {
                books.isActive = true;
                books.UpdateDate = DateTime.UtcNow;
                _context.Entry(books).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _context.SaveChanges();
                message = "Update";

                return Json(message);
            }
            catch(Exception ex)
            {
                message = "Error";
                return Json(message);
            }
        }

        public IActionResult Delete([FromBody]Books books)
        {
            var message = "";
            try
            {
                var data = _context.Books.Find(books.ID);
                data.isActive = false;
                _context.Entry(data).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                _context.SaveChanges();
                message = "Delete";
                return Json(message);
            }
            catch
            {
                message = "Error";
                return Json(message);
            }
        }
    }
}

SIPUS/Views/Shared/_Headers.cshtml
<!-- Header-->
<header id="header" class="header">
    <div class="top-left">
        <div class="navbar-header">
            <a class="navbar-brand" href="./"><img src="~/images/logo.png" alt="Logo"></a>
            <a class="navbar-brand hidden" href="./"><img src="~/images/logo2.png" alt="Logo"></a>
            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right">
        <div class="header-menu">
            <div class="header-left">
                <button class="search-trigger"><i class="fa fa-search"></i></button>
                <div class="form-inline">
                    <form class="search-form">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                    </form>
                </div>

                <div class="dropdown for-notification">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-bell"></i>
                        <span class="count bg-danger">3</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="notification">
                        <p class="red">You have 3 Notification</p>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-check"></i>
                            <p>Server #1 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-info"></i>
                            <p>Server #2 overloaded.</p>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <i class="fa fa-warning"></i>
                            <p>Server #3 overloaded.</p>
                        </a>
                    </div>
                </div>

                <div class="dropdown for-message">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-envelope"></i>
                        <span class="count bg-primary">4</span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="message">
                        <p class="red">You have 4 Mails</p>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="~/images/avatar/1.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jonathan Smith</span>
                                <span class="time float-right">Just now</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="~/images/avatar/2.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Jack Sanders</span>
                                <span class="time float-right">5 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="~/images/avatar/3.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Cheryl Wheeler</span>
                                <span class="time float-right">10 minutes ago</span>
                                <p>Hello, this is an example msg</p>
                            </div>
                        </a>
                        <a class="dropdown-item media" href="#">
                            <span class="photo media-left"><img alt="avatar" src="~/images/avatar/4.jpg"></span>
                            <div class="message media-body">
                                <span class="name float-left">Rachel Santos</span>
                                <span class="time float-right">15 minutes ago</span>
                                <p>Lorem ipsum dolor sit amet, consectetur</p>
                            </div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="~/images/admin.jpg" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>

                    <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                    <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                    <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>
                </div>
            </div>

        </div>
    </div>
</header>
<!-- /#header -->

SIPUS/Views/Shared/_Layout.cshtml
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
 <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Ela Admin - HTML5 Admin Template</title>
    <meta name="description" content="Ela Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="https://i.imgur.com/QRAUqs9.png">
    <link rel="shortcut icon" href="https://i.imgur.com/QRAUqs9.png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/assets/css/cs-skin-elastic.css">
    <link rel="stylesheet" href="~/assets/css/lib/datatable/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">

    @*datetime*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" />

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>


    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
    <link href="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/jqvmap@1.5.1/dist/jqvmap.min.css" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/weathericons@2.1.0/css/weather-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.css" rel="stylesheet" />

    <style>
        #weatherWidget .currentDesc {
            color: #ffffff !important;
        }

        .traffic-chart {
            min-height: 335px;
        }

        #flotPie1 {
            height: 150px;
        }

            #flotPie1 td {
                padding: 3px;
            }

            #flotPie1 table {
                top: 20px !important;
                right: -10px !important;
            }

        .chart-container {
            display: table;
            min-width: 270px;
            text-align: left;
            padding-top: 10px;
            padding-bottom: 10px;
        }

        #flotLine5 {
            height: 105px;
        }

        #flotBarChart {
            height: 150px;
        }

        #cellPaiChart {
            height: 160px;
        }

        body { padding-right: 0 !important }
    </style>
</head>

<body>
    <!-- Left Panel -->
    @Html.Partial("_SideBar")
    <!-- /#left-panel -->
    <!-- Right Panel -->
    <div id="right-panel" class="right-panel">

        <!-- Header-->
        @Html.Partial("_Headers")
        <!-- /#header -->
        <!-- Content -->
        @RenderBody()
        <!-- /.content -->
        <div class="clearfix"></div>
        <!-- Footer -->
        <footer class="site-footer">
            <div class="footer-inner bg-white">
                <div class="row">
                    <div class="col-sm-6">
                        Copyright &copy; 2018 Ela Admin
                    </div>
                    <div class="col-sm-6 text-right">
                        Designed by <a href="https://colorlib.com">Colorlib</a>
                    </div>
                </div>
            </div>
        </footer>
        <!-- /.site-footer -->
    </div>
  
    <!-- /#right-panel -->
    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
    <script src="~/assets/js/main.js"></script>

    @*Datatables*@
    <script src="~/assets/js/lib/data-table/datatables.min.js"></script>
    <script src="~/assets/js/lib/data-table/dataTables.bootstrap.min.js"></script>
    <script src="~/assets/js/lib/data-table/dataTables.buttons.min.js"></script>
    <script src="~/assets/js/lib/data-table/buttons.bootstrap.min.js"></script>
    <script src="~/assets/js/lib/data-table/jszip.min.js"></script>
    <script src="~/assets/js/lib/data-table/vfs_fonts.js"></script>
    <script src="~/assets/js/lib/data-table/buttons.html5.min.js"></script>
    <script src="~/assets/js/lib/data-table/buttons.print.min.js"></script>
    <script src="~/assets/js/lib/data-table/buttons.colVis.min.js"></script>
    <script src="~/assets/js/init/datatables-init.js"></script>

    @*datetime*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

    @*<!--  Chart js -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.3/dist/Chart.bundle.min.js"></script>

        <!--Chartist Chart-->
        <script src="https://cdn.jsdelivr.net/npm/chartist@0.11.0/dist/chartist.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chartist-plugin-legend@0.6.2/chartist-plugin-legend.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/jquery.flot@0.8.3/jquery.flot.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/flot-pie@1.0.0/src/jquery.flot.pie.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/flot-spline@0.0.1/js/jquery.flot.spline.min.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/simpleweather@3.1.0/jquery.simpleWeather.min.js"></script>
        <script src="~/assets/js/init/weather-init.js"></script>

        <script src="https://cdn.jsdelivr.net/npm/moment@2.22.2/moment.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.9.0/dist/fullcalendar.min.js"></script>
        <script src="~/assets/js/init/fullcalendar-init.js"></script>*@

    <!--Local Stuff-->
    <script type="text/javascript">

        //#region document ready
        $(document).ready(function() {

            $('#tbl-books').DataTable();

            //$('#year-insert').click(function () {
            //    $('#year-insert').datepicker({
            //      uiLibrary: 'bootstrap4',
            //      locale: 'es-es',
            //    });
            //});

            $('.date').datetimepicker({
                format: 'MM/DD/YYYY'
            });

            LoadData();
        });
        //#endregion

        //#region convert datetime to year only
        function ConvertDate(Inputdate)
        {
            var date = new Date(Date.parse(Inputdate));
            var year = date.getFullYear();
            //var date = year + "-" + month + "-" + day;

            return year;
        }
        //#endregion

        //#region datetime to dd/mm/yyyy
        function ConvertDateFull(Inputdate)
        {
            var date = moment(Inputdate).format("MM/DD/YYYY");

            return date;
        }
        //#endregion

        //#region load data all table
        function LoadData() {
            $("#tbl-books").DataTable({
            destroy: true,
            ajax: {
                url: "@Url.Action("GetDataBooks","Books")",
                type: "GET",
                dataType: "json",
                dataSrc: "data",
                },
                columnDefs: [{
                    "targets": [4],
                        "render": function (data, type, row) {
                            return '' + ConvertDate(data) + '';
                        }
                }],
                columns: [
                    { title: "ID", "data": "ID", "searchable": true },
                    { title: "Books Name", "data": "Name", "searchable": true },
                    { title: "Author", "data": "Author", "searchable": true },
                    { title: "Publisher", "data": "Publisher", "searchable": true },
                    { title: "Publication Year", "data": "PublicationYear", "searchable": true },
                    { title: "Rak Number", "data": "RakNumber", "searchable": true },
                    {
                        title: "Options",
                        render: function (data, type, full, meta) {
                            return '<div class="text-center list-inline">' +
                                '<button style="margin-right:3px;" class="btn btn-warning btn-sm" id="btn-edit-books" data-toggle="modal" data-target="#EditBooks" onclick="GetById(\'' + full.ID + '\', \'' + '\Update\')"><i class="fa fa-edit inline-block" style="color:white"></i></button>' +
                                        '<button class="btn btn-danger btn-sm" id="btn-delete-books" data-toggle="modal" data-target="#DeleteBooks" onclick="GetById(\'' + full.ID + '\', \'' + '\Delete\')"><i class="fa fa-trash inline-block"></i></button>'+
                                    '</div>';
                        }
                    },
                ],
            });
        }

        function onLoadBooks() {
            $("#tbl-books").DataTable().destroy();
            LoadData();
        }
        //#endregion

        //#region Book
        function CreateBooks() {
            var book = {
                "Name": $('#bookname-insert').val(),
                "Author": $('#author-insert').val(),
                "Publisher": $('#publisher-insert').val(),
                "PublicationYear": $('#year-insert').val(),
                "RakNumber": $('#rak-insert').val()
            };

            $.ajax({
                url: "@Url.Action("Create","Books")",
                data: JSON.stringify(book),
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    if (result == "Sukses") {
                        //$('#CreateBooks').modal("hide");
                        //$('#btnsave').attr("data-dismiss","modal");  
                        //$('.modal-backdrop').hide();
                        //$('body').removeClass().removeAttr('style');$('.modal-backdrop').remove();
                        LoadData();
                        ClearAll();
                    }
                }
            });
        }

        function GetById(ID,status) {
            $.ajax({
                url: '@Url.Action("GetById","Books")',
                type: "POST",
                dataType: "json",
                data: {
                    "Id" : ID
                },
                success: function (result) {
                    if (status == "Update") {
                        $('#hdnId').val(result.data.ID);
                        $('#bookname-edit').val(result.data.Name);
                        $('#author-edit').val(result.data.Author);
                        $('#publisher-edit').val(result.data.Publisher);
                        $('#year-edit').val(ConvertDateFull(result.data.PublicationYear));
                        $('#rak-edit').val(result.data.RakNumber);
                    } else if (status == "Delete") {
                        $('#hdnIdDelete').val(result.data.ID);
                    }

                }
            });
        }

        function UpdateBooks() {
            var book = {
                "ID": $('#hdnId').val(),
                "Name": $('#bookname-edit').val(),
                "Author": $('#author-edit').val(),
                "Publisher": $('#publisher-edit').val(),
                "PublicationYear": $('#year-edit').val(),
                "RakNumber": $('#rak-edit').val()
            };

            $.ajax({
                url: "@Url.Action("Update","Books")",
                data: JSON.stringify(book),
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    if (result == "Update") {
                        LoadData();
                    }
                }
            });
        }

        function DeleteBooks() {

            var book = {
                "ID": $('#hdnIdDelete').val()
            };

            $.ajax({
                url: "@Url.Action("Delete","Books")",
                data: JSON.stringify(book),
                type: "POST",
                contentType: "application/json",
                dataType: "json",
                success: function (result) {
                    if (result == "Delete") {
                        LoadData();
                    }
                }
            });
        }

        function ClearAll() {
            $('#bookname-insert').val("");
            $('#author-insert').val("");
            $('#publisher-insert').val("");
            $('#year-insert').val("");
            $('#rak-insert').val("");
        }
        //#endregion
    </script>
</body>
</html>

SIPUS/Views/Shared/_Modals.cshtml
<div class="modal fade" id="@ViewBag.ID" tabindex="-1" role="dialog" aria-labelledby="mediumModalLabel" aria-hidden="true">
    <div class="modal-dialog @ViewBag.Size" role="document">
        <div class="modal-content">
            @RenderBody()
        </div>
    </div>
</div>

SIPUS/Views/Shared/_Sidebar.cshtml
<!-- Left Panel -->
<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="@Url.Action("Index","Books")"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                </li>
                <li class="menu-title">Data</li><!-- /.menu-data -->
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-table"></i>Data Master</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-table"></i><a href="@Url.Action("Index","Books")">Books</a></li>
                        <li><i class="fa fa-table"></i><a href="ui-badges.html">Member</a></li>
                        <li><i class="fa fa-table"></i><a href="ui-tabs.html">Employees</a></li>
                    </ul>
                </li>

                <li class="menu-title">Icons</li><!-- /.menu-transaction -->
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-bar-chart"></i>Transaction</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-bar-chart"></i><a href="tables-basic.html">Loan Transaction</a></li>
                        <li><i class="fa fa-bar-chart"></i><a href="tables-data.html">Return Transaction</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>
<!-- /#left-panel -->